apiVersion: v1
kind: Service
metadata:
  name: wordpress1
  labels:
    app: wordpress1
spec:
  ports:
    - port: 80
  selector:
    app: wordpress1
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress1
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 210Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: wordpress1
spec:
  tls:
  - hosts:
    - wordpress1.devopss.tk
    secretName: wordpress1-app-tls
  rules:
  - host: wordpress1.devopss.tk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: wordpress1
            port: 
              number: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress1
  labels:
    app: wordpress1
spec:
  serviceName: wordpress1
  selector:
    matchLabels:
      app: wordpress1
      tier: frontend
  #strategy:
    #type: Recreate
  template:
    metadata:
      labels:
        app: wordpress1
        tier: frontend
    spec:
      containers:
      - image: nishit2408/hello-gitops
        name: wordpress1
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress1
        volumeMounts:
        - name: wordpress1-persistent-storage
          mountPath: /var/www/html/wordpress
      volumes:
      - name: wordpress1-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      imagePullSecrets:
      - name: my-registry-creds