
name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build wordpress
      run: |
        docker build ./wordpress-dockerfile -t nishit2408/wordpress:1.0.0
    - name: docker push
      run: |
        docker push nishit2408/wordpress:1.0.0


